require('plugins')
require('options')
require('keymaps')
require('lualine-config')
require('bufferline-config')
require('nvim-tree-config')
require('treesitter-config')
require('autopairs-config')
require('telescope-config')
require('whichkey-config')
require('colorizer-config')
require('gitsigns-config')
require('indent-blankline-config')
require('toggleterm-config')
require('comment-config')
require('lsp')

vim.cmd[[colorscheme tokyonight]]
